version: "3.8"
services:
  nodecli: 
    image: nodecli
    container_name: nodecli
    restart: always
    ports:
        - "4001:4001"
    networks:
      - app-network
    volumes:       
      - ./client:/home/node/app 

  nodeserv: 
    image: nodeserv
    container_name: nodeserv
    restart: always
    ports:
        - "4000:4000"
    networks:
      - app-network
    volumes:       
      - ./server:/home/node/app       

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:       
      - ./server:/var/wwww/html/server
      - ./client:/var/wwww/html/client   
          
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: 123456
    networks:
      - app-network

  mongoexpress:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dev
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
    networks:
      - app-network  

  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server --requirepass 123456
    ports:
    - "6379:6379"
    networks:
      - app-network
        
#Docker Networks
networks:
  app-network:
    driver: bridge        